package:
  name: cn_ws
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  #git_url: https://github.com/cn-ws/cn-ws.git
  #git_rev: {{ DRONE_COMMIT_SHA }}
  path: .

build:
 number: {{ DRONE_BUILD_NUMBER }}
 script_env:
   - DRONE_BUILD_NUMBER
   - DRONE_COMMIT_SHA

requirements:
  build:
  run:

about:
  home: https://docs.fluves.net/cn_ws/
