package:
  name: cn_ws
  version: "{{ GIT_DESCRIBE_TAG }}_{{ GIT_BUILD_STR }}"

source:
  #git_url: https://github.com/watem-sedem/watem-sedem.git
  #git_rev: {{ DRONE_COMMIT_SHA }}
  path: ..

build:
 number: {{ DRONE_BUILD_NUMBER }}
 script_env:
   - DRONE_BUILD_NUMBER
   - DRONE_COMMIT_SHA

requirements:
  build:
  run:

about:
  home: https://watem-sedem.github.io/watem-sedem/
