---
name: windows build

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "3.0"
          with-cache: true
      - name: fetch tags
        run: |
          git fetch --tags
          git lfs pull

      - name: Get Git Tag
        id: get_tag
        run: |
          echo "::set-output name=tag::$(git describe --abbrev=4 --always --tags)"
      
      - name: Write tag to File
        run: echo "'${{ steps.get_tag.outputs.tag }}'" > watem_sedem/version.inc

      - name: build compiled version
        run: |
          echo '"${{ steps.get_tag.outputs.tag }}"' > watem_sedem/version.inc
          lazbuild.exe watem_sedem\watem_sedem.lpr
          strip.exe watem_sedem\watem_sedem.exe
      - name: run tests
        run: |
           .\testfiles\test.bat
      - uses: actions/upload-artifact@master
        with:
          name: windows-compiled
          path: watem_sedem/watem_sedem.exe
