---
name: windows build

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "3.0"
          with-cache: true
      - name: fetch tags
        run: |
          git fetch --tags
          git lfs pull

      - name: build compiled version
        run: |
          lazbuild.exe watem_sedem\watem_sedem.lpr
          strip.exe cn_ws\cn_ws.exe
      - name: run tests
        run: |
           .\testfiles\test.bat
      - uses: actions/upload-artifact@master
        with:
          name: windows-compiled
          path: watem_sedem/watem_sedem.exe
