name: build_packages

on:
  workflow_call:
  workflow_dispatch:

env:
  DEBIAN_RSYNC_TARGET: /appdata/static/apt/amd64
  DRONE_BUILD_NUMBER: ${{ github.run_number }}
  RSYNC_USER: docs
  RSYNC_HOST: ijzer
jobs:
  build-linux:
    runs-on: [self-hosted, linux]
    container: registry.fluves.net/drone/cn_ws/conda-cn_ws:0.1
    env:
      PYTHONPATH: ../CNWS-processing-scripts/pycnws/src
    steps:
      - uses: actions/checkout@v3
      - name: build linux
        run: |
          git fetch --tags --force
          git lfs pull
          make

      - name: test watem-sedem runs without error
        run: |
          testfiles/test.sh

      - name: CNWS-processing repo for python tests
        shell: bash
        run: |
          source /etc/profile.d/conda.sh
          conda activate cn_ws
          pytest testfiles
      - uses: actions/upload-artifact@master
        with:
          name: linux-amd64-binary
          path: watem_sedem/watem_sedem

  build-debian:
    runs-on: [self-hosted, linux]
    container: registry.fluves.net/drone/cn_ws/debian11-build
    env:
      DEBFULLNAME: "Fluves Drone CI"
      DEBEMAIL: donotreply@fluves.net
    steps:
      - uses: actions/checkout@v3
      - name: build debian package
        run : |
          git fetch --tags --force
          git lfs pull
          gbp dch --ignore-branch --new-version=$(git describe --tags) --snapshot-number=$DRONE_BUILD_NUMBER --snapshot
          debuild -b
          mkdir /package
          mv ../watem-sedem*amd64* /package
      - uses: actions/upload-artifact@master
        with:
          name: debian-output
          path: /package
          
  build-documentation:
    needs: [build-debian,build-linux]
    runs-on: [self-hosted, linux]  
    container: registry.fluves.net/drone/cn_ws/conda
    steps:
      - uses: actions/checkout@v3
      - name: fetch tags
        shell: bash
        run: |
          git fetch --tags
          git lfs pull

      - name: build website
        shell: bash
        run: |
          pip install -r ./docs/requirements.txt
          sphinx-build ./docs ./docs/_build/

      - uses: actions/upload-artifact@master
        with:
          name: documentation-output
          path: ./docs

  # build-windows:
  #   runs-on: [self-hosted, windows] 
  #   container: registry.fluves.net/drone/cn_ws/lazarus-windows
  #   steps: 
  #     - uses: actions/checkout@v3
  #     - name: fetch tags
  #       run: |
  #         git fetch --tags 
  #         git lfs pull

  #     - name: build compiled version
  #       run: |
  #         c:\lazarus\lazbuild.exe cn_ws\cn_ws.lpr
  #         c:\lazarus\fpc\3.2.0\bin\x86_64-win64\strip.exe cn_ws\cn_ws.exe

  #     - name: run tests
  #       run: |
  #         .\testfiles\test.bat

  #     - name: build conda package
  #       run: |
  #         get-content c:/users/ContainerAdministrator/_netrc | out-file -encoding ASCII c:/users/ContainerAdministrator/_netrc_ascii
  #         del c:/users/ContainerAdministrator/_netrc
  #         mv c:/users/ContainerAdministrator/_netrc_ascii c:/users/ContainerAdministrator/_netrc
  #         conda build conda --output-folder conda_build
