name: publish_documentation

on:
  workflow_dispatch:
  pull_request:
  create:
    tags:

env:
  DRONE_BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build-packages:
    if: contains(github.event.pull_request.labels.*.name, 'documentation') || contains(github.ref , 'refs/tags/')
    uses: ./.github/workflows/build.yml

  publish-documentation:
    if: contains(github.event.pull_request.labels.*.name, 'documentation') || contains(github.ref , 'refs/tags/')
    needs: [build-packages] 
    runs-on: [self-hosted, linux] 
    env:
    steps:
      - uses: actions/download-artifact@master
        with:
          name: documentation-output
          path: ./docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3 # github actions need to be restricted
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
