name: publish_documentation

on:
  workflow_dispatch:
  pull_request:
  create:
    tags:

env:
  DRONE_BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build-packages:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build.yml

  publish-documentation:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/documentation'
    needs: [build-packages] 
    runs-on: ubuntu-latest
    container: ghcr.io/watem-sedem/ci/debian11-build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: documentation-output
          path: ./docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3 # github actions need to be restricted
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
